export default {
  LOAD_EVENTS_REQUEST: 'LOAD_EVENTS_REQUEST',
  LOAD_EVENTS_SUCCESS: 'LOAD_EVENTS_SUCCESS',
  LOAD_EVENTS_FAILED: 'LOAD_EVENTS_FAILED',
  ADD_EVENT: 'ADD_EVENT',
  ADD_EVENT_FULFILLED: 'ADD_EVENT_FULFILLED',
  ADD_EVENT_PENDING: 'ADD_EVENT_PENDING',
  ADD_EVENT_REJECTED: 'ADD_EVENT_REJECTED',
  MOCK_SIGN_IN: 'MOCK_SIGN_IN',
  MOCK_SIGN_IN_FULFILLED: 'MOCK_SIGN_IN_FULFILLED',
  MOCK_SIGN_IN_PENDING: 'MOCK_SIGN_IN_PENDING',
  MOCK_SIGN_IN_REJECTED: 'MOCK_SIGN_IN_REJECTED',
  GET_INVITE_REQUEST: 'GET_INVITE_REQUEST',
  GET_INVITE_SUCCESS_EMPTY_EVENT_INFO: 'GET_INVITE_SUCCESS_EMPTY_EVENT_INFO',
  GET_INVITE_SUCCESS: 'GET_INVITE_SUCCESS',
  GET_INVITE_FAILED: 'GET_INVITE_FAILED'
};
